{
 "title": "JWT Pizza",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "rate(PUT_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "PUT"
    },
    {
     "expr": "rate(DELETE_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(GET_total[$__rate_interval])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(OPTIONS_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "OPTIONS"
    },
    {
     "expr": "rate(POST_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "POST"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(fulfilled_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(failure_total[$__rate_interval])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "rate(authorized_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Authorized"
    },
    {
     "expr": "rate(unauthorized_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Unauthorized"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(request_latency_milliseconds{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "rate(order_fulfillment_time_milliseconds{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}